dist: trusty
sudo: required

language: python
python:
  - "3.6"

env:
  - SKIP_NETWORK_TESTS=0

install:
    - travis_retry pip install tox
    # XXX Avoid snapcraft from loading useless libs when running on Ubuntu
    - sudo truncate -s 0 /etc/os-release
script:
    - TOX_ENVIRONMENT="py${TRAVIS_PYTHON_VERSION//./}"
    - tox -e "$TOX_ENVIRONMENT"
after_success:
- if [[ $TOX_ENVIRONMENT == 'py36' ]] ; then tox -e py36-coveralls; else echo "No coverage to do"; fi
