dist: trusty
sudo: required

language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      dist: trusty
      env: TOXENV=py36
      sudo: false
    - python: 3.7
      # from https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442
      dist: xenial
      env: TOXENV=py37
      sudo: true

env:
  - SKIP_NETWORK_TESTS=0

install:
    - travis_retry pip install tox
    # XXX Avoid snapcraft from loading useless libs when running on Ubuntu
    - sudo truncate -s 0 /etc/os-release
script:
    - TOX_ENVIRONMENT="py${TRAVIS_PYTHON_VERSION//./}"
    - tox -e "$TOX_ENVIRONMENT"
after_success:
- if [[ $TOX_ENVIRONMENT == 'py36' ]] ; then tox -e py36-coveralls; else echo "No coverage to do"; fi
